### ISSUE TITLE
presign should not include payload hash

### ISSUE THREAD

**Issue by arshrahman** [jakub-bacic/aws_auth#2]
First, thank you for creating this package. This is by far, the most lightweight and simple package to add aws v4 signature.

The signing with authorization header works correctly but the presigning with url doesn't work. AWS return 403 with `SignatureDoesNotMatch` error for presigning with query url. After digging through the code, I found that presigning with query url is also calling `getHashedPayload()`. 

From AWS documentation, the correct way for presigning is to just use a constant string `UNSIGNED-PAYLOAD` as payload

> You don't include a payload hash in the Canonical Request, because when you create a presigned URL, you don't know the payload content because the URL is used to upload an arbitrary payload. Instead, you use a constant string UNSIGNED-PAYLOAD.

https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

After changing `getCanonicalRequest()` function slightly like below, presigning works 

```
  String getCanonicalRequest([bool preSign]) {
    var result = <String>[
      method.toUpperCase(),
      getCanonicalUri(),
      getCanonicalQueryString(),
      getCanonicalHeaders(),
      getSignedHeaders(),
      (preSign) ? 'UNSIGNED-PAYLOAD' : getHashedPayload(),
    ];
    return result.join('\n');
  }
```

**Comment by jakub-bacic** [comment]
> This is by far, the most lightweight and simple package to add aws v4 signature.

I'm glad you like it. That was actually my intention to make it as lightweight as possible (that's why there's no HTTP library dependency for example) 😊. 

Regarding the issue you described, I think it's related to S3 endpoints. I know they are a little bit different from other AWS endpoints (at least looking at the implementation in other languages) and I haven't tested my package against them. Could you share an example request that didn't work for you? I'll try to take a look at that.

**Comment by jakub-bacic** [comment]
@arshrahman
Version `2.0.0` has optional parameter `signPayload` in `presign` method of the signer. It defaults to false in case of S3 service.

Please keep in mind that this major version contains two non-backward compatible changes:
- migration to null safety
- `AWS4Signer` expects `AWSCredentialsProvider` interface object now instead of raw `AWSCredentials` object
